# Generated by Django 4.1.1 on 2022-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_alter_donate_card_number_alter_donate_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donate',
            name='cvv',
            field=models.IntegerField(),
        ),
    ]
