# Generated by Django 4.1.1 on 2022-10-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_alter_donate_card_number_alter_donate_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
