# Generated by Django 4.1.1 on 2022-10-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_donate_donate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='user',
        ),
    ]
